### ISSUE TITLE
Poke the bear kind of feature

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/caen_tools#12]
Попов просит/требует добавить фичу в SysCheck, которая раз в некоторый промежуток времени period (задаётся в конфиге), снижает напряжение как на интерлоке на check_time (задаётся тоже в конфиге), а потом обратно поднимает.
Для этого нужен +1 скрипт в SysCheck.

@nikita-p Сможешь сделать?

![image](https://github.com/user-attachments/assets/6772e25d-ffbe-4e3d-b14e-f5a935edd575)

**Comment by nikita-p** [comment]
Да, окей
