### ISSUE TITLE
SND db connection error

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/caen_tools#15]
@nikita-p Интерлок не чита
[2024-09-30 14:08:03] WARNING in interlockdb.py:53:: Interlock reading problem (from SND db)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/caen_tools/SystemCheck/utils/interlockdb.py", line 41, in get_interlock
    async with await psycopg.AsyncConnection.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection_async.py", line 114, in connect
    attempts = await conninfo_attempts_async(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts_async.py", line 49, in conninfo_attempts_async
    raise e.OperationalError(str(last_exc))
psycopg.OperationalError: [Errno -2] Name does not resolve

**Comment by nikita-p** [comment]
ок, сейчас проверю

**Comment by nikita-p** [comment]
тут ещё вопрос, доступна ли база вообще, может я где-то туплю, но с `dq11` без всяких докеров такой ответ
```bash
$ psql "postgresql://...
psql: could not connect to server: No route to host
	Is the server running on host "sndas0" (192.168.170.37) and accepting
	TCP/IP connections on port 5432?
```

(к другим постгрес базам коннект нормальный)

**Comment by AliensWithdrawPeople** [comment]
Использовать для считывания интерлока пакет /daqhome/cmd3daq/pyslowfe/vepp2kCAS.py.
Смотреть пример в  /daqhome/cmd3daq/pyslowfe/veppcasgroup.py.

**Comment by nikita-p** [comment]
@AliensWithdrawPeople 
проблема в докер-контейнере

используем стандартный network, связывающий наши контейнеры
```bash
$ docker run --rm --network dq11_default -it syscheck:dev sh
/ # ping sndas0
ping: bad address 'sndas0'
```

в то же время не используя network
```bash
$ docker run --rm -it syscheck:dev sh
/ # ping sndas0
PING sndas0 (192.168.170.37): 56 data bytes
64 bytes from 192.168.170.37: seq=0 ttl=63 time=0.427 ms
^C
--- sndas0 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.427/0.427/0.427 ms
```

**Comment by nikita-p** [comment]
оказывается, что коннект с базой снд довольно медленный

из логов check.log (за 21.10)

> [2024-10-21 11:29:52] INFO in interlock.py:41:: InterlockControl was done in 1.974 s
> [2024-10-21 11:29:55] INFO in interlock.py:41:: InterlockControl was done in 2.183 s
> [2024-10-21 11:29:56] INFO in interlock.py:41:: InterlockControl was done in 1.870 s
> [2024-10-21 11:29:58] INFO in interlock.py:41:: InterlockControl was done in 1.766 s
> [2024-10-21 11:30:01] INFO in interlock.py:41:: InterlockControl was done in 2.391 s
> [2024-10-21 11:30:03] INFO in interlock.py:41:: InterlockControl was done in 2.183 s
> [2024-10-21 11:30:04] INFO in interlock.py:41:: InterlockControl was done in 1.661 s
> [2024-10-21 11:30:06] INFO in interlock.py:41:: InterlockControl was done in 1.767 s

Логика InterlockControl: он получает значение из базы снд и отправляет соотв. статус на MChS

**Comment by AliensWithdrawPeople** [comment]
Bruh... Я завтра поговорю с кем-нибудь с ВЭПП, чтобы прямой конект настроить. Но боюсь быстро ничего не будет сделано.

**Comment by nikita-p** [comment]
возможно это повысит скорость; надо конечно проверить, но интуитивно кажется, что сейчас большая часть времени тратится именно на подключение к базе

завтра попробую потестить

> Использовать для считывания интерлока пакет /daqhome/cmd3daq/pyslowfe/vepp2kCAS.py. Смотреть пример в /daqhome/cmd3daq/pyslowfe/veppcasgroup.py.

**Comment by AliensWithdrawPeople** [comment]
Если там под капотом также в постгресс базу на sndas0 лазят, то это вряд ли даст выйгрыш.
Буду рад ошибиться.

**Comment by AliensWithdrawPeople** [comment]
Из под docker-а интерлок по сокету не читается. 
Я попробовал напрямую на dq11 запросить интерлок. Ниже код, который использовал:
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("sndas0.inp.nsk.su", 20041))
s.sendall(b"REQUEST: 'n:CMD/Interlock|m:get'\n")
chunk = s.recv(4096)
print(chunk.decode("utf-8"))

Ответ многозначительное нет:
> descr:name field not found|name:error|time_:24.10.2024 23_51_02.474

@nikita-p  можешь чекнуть это дело. У тебя ведь получалось как-то читать его.

**Comment by nikita-p** [comment]
сейчас накидаю всё, что у меня есть

вот такой код в контейнере проходит:
```bash
docker run --rm -it monitor:dev python
```

```python
import zmq

ctx = zmq.Context()
socket = ctx.socket(zmq.STREAM)
socket.setsockopt(zmq.RCVTIMEO, 1000)

connect_address = "tcp://sndas0:20041"
socket.connect(connect_address)
s0 = bytes("n:CMD/Interlock|m:get\n", encoding="UTF-8")

id_sock = socket.getsockopt(zmq.IDENTITY)
socket.send(id_sock, zmq.SNDMORE)
socket.send(s0)

message = socket.recv_multipart()
message2 = socket.recv_multipart()
print(message, message2)
# [b'\x00\x00\x00\x00\x00', b''] [b'\x00\x00\x00\x00\x00', b'name:CMD/Interlock|time:24.10.2024 23_07_06.144|val:1\n']
socket.close()
```

или в терминах `socket`:

```python
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
sock.connect(("sndas0", 20041))  
sock.send(bytes("n:CMD/Interlock|m:get\n", encoding="UTF-8"))  
data = sock.recv(4096)  
sock.close() 
print(data)
# b'name:CMD/Interlock|time:24.10.2024 23_07_06.144|val:1\n'
```

второй вариант напрямую прошёл

**Comment by nikita-p** [comment]
кажется понял проблему:

здесь я зря использую `r`-строку, из-за неё неправильное сообщение
https://github.com/caenHV/caen_tools/blob/6399275a063e24427805ffa3abc97e57b0aec7c0/caen_tools/SystemCheck/utils/interlockdb.py#L67

сейчас отсылается
`b'n:CMD/Interlock|m:get\\n'`
а должно
`b'n:CMD/Interlock|m:get\n'`
