### ISSUE TITLE
Wish list Попова

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/caen_tools#17]
@nikita-p 
Мне тут Попов список требований выкатил. Представляю на суд общественности (с моим примечаниями и смысловыми правками --- прим. посыльного):
1) Скорости подъёма должны быть пропорциональны уставкам (был баг в caen-setup модуле. Исправлен в [caen-setup v1.2.3](https://github.com/caenHV/Setup/releases/tag/v1.2.3) и [caen_tools v2.3.2](https://github.com/caenHV/caen_tools/tree/v2.3.2))
2) Должно выводиться сообщения с причиной снятия напряжения
3) Сделать код без докера (Нет!!! Я против.)
4) Добавить документацию: что как работает, что где лежит. (Репорт по работе писать я не хочу. Описать расположение конфигов и смысол параметров в них я готов)
5) Readme со спиком системных комманд.
6) Какая защита от дурака? (от одного мне.нам никак не защититься)
7) Комманда для переустановки драйвера. (Готов написать скрипт, который автоматизирует процедуру)

![image](https://github.com/user-attachments/assets/0c25e1be-6ba1-49b6-ba4a-2b86bccb06b7)

По поводу 7), было бы неплохо придумать, как извне автоматизировано понять, что нужно менять драйверы. Так можно было бы системного демона сваять, который это делал совсем на автомате.

**Comment by nikita-p** [comment]
1. :+1:
2. в целом предложение обоснованное, тут интересно подумать: а если писать в ELog такие вещи напрямую? и возможно ли это? 
3. не думаю, что без докера станет проще кому-то
4. да, спасибо, плюс, думаю, что после нескольких недель работы проги нам стоит собраться и какие-нибудь слайды быстро накидать и показать
5. это примерно как 4-й пункт, я там где-то уже начинал Readme обновлять, можно будет продолжить, просто пока система не в рабочем режиме не совсем понятно, что надо из команд (compose up/down только)
6. :cry: в целом сейчас уже нельзя выставлять слишком высокие напряжения, нельзя вводить бред в поле установки, напряжение выставляется с фиксированной скоростью, происходит аварийное отключение в критические моменты, да и вообще весь интерфейс выглядит как айфон (в смысле минимум настроек и делай только то, что разрешили), а если продвинутый пользователь, то ему **root** доступ к *dq11* (или доступ к группе docker), он может редактировать конфиг; 
да и вообще, тот же вопрос можно и к существующему HVMonitor задать, какая там защита; а какая защита от того, что я сейчас в консоли оператора начну тыкать все кнопки, которые там есть? (вопрос риторический)
7. скрипт это хорошо, но да, тут надо подумать и понять, как это должно выглядеть (ещё в compose прописать перезапуск сервисов при перезагрузке *dq11*)
