### ISSUE TITLE
Implement breakdown behaviour

### ISSUE THREAD

**Issue by nikita-p** [caenHV/caen_tools#18]
сделать сценарий на пробой

**Comment by AliensWithdrawPeople** [comment]
Попов требует/просит, чтобы это дело было сделано до начала записи физических заходов, то есть до понедельника. 
Также он внёс доп условие: автоматом напряжение должно подниматься только в том случае, если за последние K минут было менее N сбросов напряжения. В противном случае с концами сбрасывать напряжение.
