### ISSUE TITLE
Write statuses to monitor

### ISSUE THREAD

**Issue by nikita-p** [caenHV/caen_tools#19]

**Comment by AliensWithdrawPeople** [comment]
@nikita-p 
Добавил в [b8679ad](https://github.com/caenHV/caen_tools/commit/b8679ad74b12fba0ef967936c3db705ecab88ad0) реализацию.
В соответствующем README уже прописаны пути, но продублирую добавленные рауты и здесь.

**Сейчас так:** Статус установки это булевый is_ok  и стринговое описание description (если is_ok == True, то резонно отправлять пустую строку imo). Данные параметры пишутся в таблицу status в monitor.db и в файл status_file_path (см. обновлённый config.ini). 
Помимо прочего я увеличил период очистки monitor.db с одного дня до трёх. Кажется, что 150MB файл не проблема.

<details>
 <summary><code>Post</code> <code><b>send_status</b></code> 
 <code>(writes the status of the CAEN device to the own DB and online database)</code></summary>

##### Parameters

> | name |  type   | data type  | description |
> |------|-----|---------|-----------------|
> | is_ok |  required | bool   | The status of the setup |
> | description |  required | str   | Explanation of the status. Meaningful only if is_ok == False |

</details>

</details>

<details>
 <summary><code>GET</code> <code><b>get_status</b></code>
 <code>(retrieves historical setup's statuses from the our own DB)</code></summary>

##### Parameters

> | name |  type   | data type  | description |
> |------|-----|---------|-----------------|
> | start_time |  required | int   | Start timestamp of requested info (in seconds from the Epoch) |
> | end_time |  optional | int   | End timestamp of requested info (in seconds from the Epoch), default is current timestamp  |

</details>

**Comment by nikita-p** [comment]
в ближайшее время постараюсь прикрутить новые методы к веб-странице
